server:
  port: ${JAVA_PORT_DEFAULT:8080}
#
spring:
  application:
    name: "DMS"
  # JDBC config
  datasource:
#    url: ${DB_URL:jdbc:postgresql://35.240.252.35:5432/postgres}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:rbking123}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rbking123}
    driver-class-name: org.postgresql.Driver
    hikari:
      enabled: true
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    #        globally_quoted_identifiers: true
    open-in-view: false
    show-sql: false

bezkoder:
  app:
    jwtSecret: ${JWT_SECRET:secret}
    jwtExpirationMs: ${JWT_EXPIRATION:86400000}
    refreshTokenExpirationMs: ${REFRESH_TOKEN_EXPIRATION:864000000}

redis:
  host: localhost
  port: 6379
  password: ${REDIS_PASSWORD:123456}
  expired: ${REDIS_EXPIRED:3600000}

permission:
  url-link: ${SET_PERMISSION:asddfsd}